FROM microsoft/dotnet:7.0 as base
WORKDIR /app
EXPOSE 5001

FROM microsoft/dotnet:7.0 AS build
WORKDIR /src
COPY Sender/Sender.csproj Sender/
RUN dotnet restore Sender/Sender.csproj
COPY . .
WORKDIR /src/Sender
RUN dotnet build Sender.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Sender.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Sender.dll"]
